"""add tables

Revision ID: 6237c3183214
Revises: 
Create Date: 2024-09-18 11:39:44.670633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6237c3183214'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('director', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_movies'))
    )
    op.create_table('theaters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_theaters'))
    )
    op.create_table('showtimes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('theater_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], name=op.f('fk_showtimes_movie_id_movies')),
    sa.ForeignKeyConstraint(['theater_id'], ['theaters.id'], name=op.f('fk_showtimes_theater_id_theaters')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_showtimes'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('showtimes')
    op.drop_table('theaters')
    op.drop_table('movies')
    # ### end Alembic commands ###
